version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: '14:06'
      timezone: Europe/Zurich
    groups:
       actions:
          patterns: ['*']
