version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: '13:00'
      timezone: Europe/Zurich
    groups:
       github-actions:
          patterns: ['*']
